package br.com.concessionaria.model;

// Generated 11/07/2013 17:45:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Endereco generated by hbm2java
 */
@Entity
@Table(name = "endereco", catalog = "concessionaria")
public class Endereco implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 822645577916414100L;
	private Integer idendereco;
	private String logradouro;
	private String numero;
	private String bairro;
	private String cidade;
	private String uf;
	private String CEP;
	private String complemento;
	private Set<Pessoajuridica> pessoajuridicas = new HashSet<Pessoajuridica>(0);
	private Set<Pessoafisica> pessoafisicas = new HashSet<Pessoafisica>(0);

	public Endereco() {
	}

	public Endereco(String logradouro, String numero, String bairro,
			String cidade, String uf, String complemento,
			Set<Pessoajuridica> pessoajuridicas, Set<Pessoafisica> pessoafisicas) {
		this.logradouro = logradouro;
		this.numero = numero;
		this.bairro = bairro;
		this.cidade = cidade;
		this.uf = uf;
		this.complemento = complemento;
		this.pessoajuridicas = pessoajuridicas;
		this.pessoafisicas = pessoafisicas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idendereco", unique = true, nullable = false)
	public Integer getIdendereco() {
		return this.idendereco;
	}

	public void setIdendereco(Integer idendereco) {
		this.idendereco = idendereco;
	}

	@Column(name = "logradouro", length = 60)
	public String getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	@Column(name = "numero", length = 15)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "bairro", length = 20)
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@Column(name = "cidade", length = 20)
	public String getCidade() {
		return this.cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	@Column(name = "uf", length = 2)
	public String getUf() {
		return this.uf;
	}

	public void setUf(String uf) {
		this.uf = uf;
	}

	@Column(name = "complemento", length = 20)
	public String getComplemento() {
		return this.complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "endereco")
	public Set<Pessoajuridica> getPessoajuridicas() {
		return this.pessoajuridicas;
	}

	public void setPessoajuridicas(Set<Pessoajuridica> pessoajuridicas) {
		this.pessoajuridicas = pessoajuridicas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "endereco")
	public Set<Pessoafisica> getPessoafisicas() {
		return this.pessoafisicas;
	}

	public void setPessoafisicas(Set<Pessoafisica> pessoafisicas) {
		this.pessoafisicas = pessoafisicas;
	}

	public String getCEP() {
		return CEP;
	}

	public void setCEP(String cEP) {
		CEP = cEP;
	}

}
