package br.com.concessionaria.model;

// Generated 11/07/2013 17:45:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Veiculo generated by hbm2java
 */
@Entity
@Table(name = "veiculo", catalog = "concessionaria")
public class Veiculo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 985351531513165338L;
	private Integer idveiculo;
	private Combustivel combustivel;
	private String modelo;
	private String marca;
	private Date anomodelo;
	private Date anofabricacao;
	private Integer quilometragem;
	private Set<Locacao> locacaos = new HashSet<Locacao>(0);
	private Set<Venda> vendas = new HashSet<Venda>(0);
	private Set<Compra> compras = new HashSet<Compra>(0);
	private Set<Manutencao> manutencaos = new HashSet<Manutencao>(0);

	public Veiculo() {
	}

	public Veiculo(Combustivel combustivel) {
		this.combustivel = combustivel;
	}

	public Veiculo(Combustivel combustivel, String modelo, String marca,
			Date anomodelo, Date anofabricacao, Integer quilometragem,
			Set<Locacao> locacaos, Set<Venda> vendas, Set<Compra> compras,
			Set<Manutencao> manutencaos) {
		this.combustivel = combustivel;
		this.modelo = modelo;
		this.marca = marca;
		this.anomodelo = anomodelo;
		this.anofabricacao = anofabricacao;
		this.quilometragem = quilometragem;
		this.locacaos = locacaos;
		this.vendas = vendas;
		this.compras = compras;
		this.manutencaos = manutencaos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idveiculo", unique = true, nullable = false)
	public Integer getIdveiculo() {
		return this.idveiculo;
	}

	public void setIdveiculo(Integer idveiculo) {
		this.idveiculo = idveiculo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcombustivel", nullable = false)
	public Combustivel getCombustivel() {
		return this.combustivel;
	}

	public void setCombustivel(Combustivel combustivel) {
		this.combustivel = combustivel;
	}

	@Column(name = "modelo", length = 30)
	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	@Column(name = "marca", length = 30)
	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "anomodelo", length = 10)
	public Date getAnomodelo() {
		return this.anomodelo;
	}

	public void setAnomodelo(Date anomodelo) {
		this.anomodelo = anomodelo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "anofabricacao", length = 10)
	public Date getAnofabricacao() {
		return this.anofabricacao;
	}

	public void setAnofabricacao(Date anofabricacao) {
		this.anofabricacao = anofabricacao;
	}

	@Column(name = "quilometragem")
	public Integer getQuilometragem() {
		return this.quilometragem;
	}

	public void setQuilometragem(Integer quilometragem) {
		this.quilometragem = quilometragem;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "veiculo")
	public Set<Locacao> getLocacaos() {
		return this.locacaos;
	}

	public void setLocacaos(Set<Locacao> locacaos) {
		this.locacaos = locacaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "veiculo")
	public Set<Venda> getVendas() {
		return this.vendas;
	}

	public void setVendas(Set<Venda> vendas) {
		this.vendas = vendas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "veiculo")
	public Set<Compra> getCompras() {
		return this.compras;
	}

	public void setCompras(Set<Compra> compras) {
		this.compras = compras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "veiculo")
	public Set<Manutencao> getManutencaos() {
		return this.manutencaos;
	}

	public void setManutencaos(Set<Manutencao> manutencaos) {
		this.manutencaos = manutencaos;
	}

}
