package com.rentstore.model;

// Generated 11/07/2013 17:45:57 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Boleto generated by hbm2java
 */
@Entity
@Table(name = "boleto", catalog = "concessionaria")
public class Boleto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4752607016020108206L;
	private Integer idboleto;
	private Pessoajuridica pessoajuridica;
	private Funcionario funcionario;
	private Pagamento pagamento;
	private String codigobarras;
	private BigDecimal valor;
	private BigDecimal valorpago;
	private Date datavencimento;
	private Date datapagamento;

	public Boleto() {
	}

	public Boleto(Pessoajuridica pessoajuridica, Funcionario funcionario,
			Pagamento pagamento) {
		this.pessoajuridica = pessoajuridica;
		this.funcionario = funcionario;
		this.pagamento = pagamento;
	}

	public Boleto(Pessoajuridica pessoajuridica, Funcionario funcionario,
			Pagamento pagamento, String codigobarras, BigDecimal valor,
			BigDecimal valorpago, Date datavencimento, Date datapagamento) {
		this.pessoajuridica = pessoajuridica;
		this.funcionario = funcionario;
		this.pagamento = pagamento;
		this.codigobarras = codigobarras;
		this.valor = valor;
		this.valorpago = valorpago;
		this.datavencimento = datavencimento;
		this.datapagamento = datapagamento;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idboleto", unique = true, nullable = false)
	public Integer getIdboleto() {
		return this.idboleto;
	}

	public void setIdboleto(Integer idboleto) {
		this.idboleto = idboleto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpessoajuridica", nullable = false)
	public Pessoajuridica getPessoajuridica() {
		return this.pessoajuridica;
	}

	public void setPessoajuridica(Pessoajuridica pessoajuridica) {
		this.pessoajuridica = pessoajuridica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idfuncemissor", nullable = false)
	public Funcionario getFuncionario() {
		return this.funcionario;
	}

	public void setFuncionario(Funcionario funcionario) {
		this.funcionario = funcionario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpagamento", nullable = false)
	public Pagamento getPagamento() {
		return this.pagamento;
	}

	public void setPagamento(Pagamento pagamento) {
		this.pagamento = pagamento;
	}

	@Column(name = "codigobarras", length = 60)
	public String getCodigobarras() {
		return this.codigobarras;
	}

	public void setCodigobarras(String codigobarras) {
		this.codigobarras = codigobarras;
	}

	@Column(name = "valor", precision = 15)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	@Column(name = "valorpago", precision = 15)
	public BigDecimal getValorpago() {
		return this.valorpago;
	}

	public void setValorpago(BigDecimal valorpago) {
		this.valorpago = valorpago;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datavencimento", length = 10)
	public Date getDatavencimento() {
		return this.datavencimento;
	}

	public void setDatavencimento(Date datavencimento) {
		this.datavencimento = datavencimento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datapagamento", length = 10)
	public Date getDatapagamento() {
		return this.datapagamento;
	}

	public void setDatapagamento(Date datapagamento) {
		this.datapagamento = datapagamento;
	}

}
