package com.rentstore.model;

// Generated 11/07/2013 17:45:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", catalog = "concessionaria")
public class Cliente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6084567436528210431L;
	private Integer idcliente;
	private Pessoafisica pessoafisica;
	private Pessoajuridica pessoajuridica;
	private Date datacadastro;
	private Set<Locacao> locacaos = new HashSet<Locacao>(0);

	public Cliente() {
	}

	public Cliente(Pessoafisica pessoafisica, Pessoajuridica pessoajuridica,
			Date datacadastro, Set<Locacao> locacaos) {
		this.pessoafisica = pessoafisica;
		this.pessoajuridica = pessoajuridica;
		this.datacadastro = datacadastro;
		this.locacaos = locacaos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idcliente", unique = true, nullable = false)
	public Integer getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(Integer idcliente) {
		this.idcliente = idcliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpessoafisica")
	public Pessoafisica getPessoafisica() {
		return this.pessoafisica;
	}

	public void setPessoafisica(Pessoafisica pessoafisica) {
		this.pessoafisica = pessoafisica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpessoajuridica")
	public Pessoajuridica getPessoajuridica() {
		return this.pessoajuridica;
	}

	public void setPessoajuridica(Pessoajuridica pessoajuridica) {
		this.pessoajuridica = pessoajuridica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datacadastro", length = 10)
	public Date getDatacadastro() {
		return this.datacadastro;
	}

	public void setDatacadastro(Date datacadastro) {
		this.datacadastro = datacadastro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<Locacao> getLocacaos() {
		return this.locacaos;
	}

	public void setLocacaos(Set<Locacao> locacaos) {
		this.locacaos = locacaos;
	}

}
