package com.rentstore.model;

// Generated 11/07/2013 17:45:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Combustivel generated by hbm2java
 */
@Entity
@Table(name = "combustivel", catalog = "concessionaria")
public class Combustivel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6072096079153281480L;
	private Integer idcombustivel;
	private String nome;
	private Set<Veiculo> veiculos = new HashSet<Veiculo>(0);

	public Combustivel() {
	}

	public Combustivel(String nome, Set<Veiculo> veiculos) {
		this.nome = nome;
		this.veiculos = veiculos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idcombustivel", unique = true, nullable = false)
	public Integer getIdcombustivel() {
		return this.idcombustivel;
	}

	public void setIdcombustivel(Integer idcombustivel) {
		this.idcombustivel = idcombustivel;
	}

	@Column(name = "nome", length = 15)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "combustivel")
	public Set<Veiculo> getVeiculos() {
		return this.veiculos;
	}

	public void setVeiculos(Set<Veiculo> veiculos) {
		this.veiculos = veiculos;
	}

}
