package com.rentstore.model;

// Generated 11/07/2013 17:45:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Manutencao generated by hbm2java
 */
@Entity
@Table(name = "manutencao", catalog = "concessionaria")
public class Manutencao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8129621682122731782L;
	private Integer idmanutencao;
	private Funcionario funcionario;
	private Veiculo veiculo;
	private Locacao locacao;
	private Date datainicio;
	private Date datatermino;
	private String observacoes;

	public Manutencao() {
	}

	public Manutencao(Funcionario funcionario, Veiculo veiculo) {
		this.funcionario = funcionario;
		this.veiculo = veiculo;
	}

	public Manutencao(Funcionario funcionario, Veiculo veiculo,
			Locacao locacao, Date datainicio, Date datatermino,
			String observacoes) {
		this.funcionario = funcionario;
		this.veiculo = veiculo;
		this.locacao = locacao;
		this.datainicio = datainicio;
		this.datatermino = datatermino;
		this.observacoes = observacoes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idmanutencao", unique = true, nullable = false)
	public Integer getIdmanutencao() {
		return this.idmanutencao;
	}

	public void setIdmanutencao(Integer idmanutencao) {
		this.idmanutencao = idmanutencao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idfunc", nullable = false)
	public Funcionario getFuncionario() {
		return this.funcionario;
	}

	public void setFuncionario(Funcionario funcionario) {
		this.funcionario = funcionario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idveiculo", nullable = false)
	public Veiculo getVeiculo() {
		return this.veiculo;
	}

	public void setVeiculo(Veiculo veiculo) {
		this.veiculo = veiculo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idlocacao")
	public Locacao getLocacao() {
		return this.locacao;
	}

	public void setLocacao(Locacao locacao) {
		this.locacao = locacao;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datainicio", length = 10)
	public Date getDatainicio() {
		return this.datainicio;
	}

	public void setDatainicio(Date datainicio) {
		this.datainicio = datainicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datatermino", length = 10)
	public Date getDatatermino() {
		return this.datatermino;
	}

	public void setDatatermino(Date datatermino) {
		this.datatermino = datatermino;
	}

	@Column(name = "observacoes", length = 50)
	public String getObservacoes() {
		return this.observacoes;
	}

	public void setObservacoes(String observacoes) {
		this.observacoes = observacoes;
	}

}
