package com.rentstore.model;

// Generated 11/07/2013 17:45:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pessoajuridica generated by hbm2java
 */
@Entity
@Table(name = "pessoajuridica", catalog = "concessionaria")
public class Pessoajuridica implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8825439714499005243L;
	private Integer idpessoajuridica;
	private Endereco endereco;
	private String razaosocial;
	private String nomefantasia;
	private String cnpj;
	private String telefone1;
	private String telefone2;
	private Set<Boleto> boletos = new HashSet<Boleto>(0);
	private Set<Cliente> clientes = new HashSet<Cliente>(0);

	public Pessoajuridica() {
	}

	public Pessoajuridica(Endereco endereco, String razaosocial,
			String nomefantasia, String cnpj, String telefone1,
			String telefone2, Set<Boleto> boletos, Set<Cliente> clientes) {
		this.endereco = endereco;
		this.razaosocial = razaosocial;
		this.nomefantasia = nomefantasia;
		this.cnpj = cnpj;
		this.telefone1 = telefone1;
		this.telefone2 = telefone2;
		this.boletos = boletos;
		this.clientes = clientes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idpessoajuridica", unique = true, nullable = false)
	public Integer getIdpessoajuridica() {
		return this.idpessoajuridica;
	}

	public void setIdpessoajuridica(Integer idpessoajuridica) {
		this.idpessoajuridica = idpessoajuridica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idendereco")
	public Endereco getEndereco() {
		return this.endereco;
	}

	public void setEndereco(Endereco endereco) {
		this.endereco = endereco;
	}

	@Column(name = "razaosocial", length = 50)
	public String getRazaosocial() {
		return this.razaosocial;
	}

	public void setRazaosocial(String razaosocial) {
		this.razaosocial = razaosocial;
	}

	@Column(name = "nomefantasia", length = 50)
	public String getNomefantasia() {
		return this.nomefantasia;
	}

	public void setNomefantasia(String nomefantasia) {
		this.nomefantasia = nomefantasia;
	}

	@Column(name = "cnpj", length = 20)
	public String getCnpj() {
		return this.cnpj;
	}

	public void setCnpj(String cnpj) {
		this.cnpj = cnpj;
	}

	@Column(name = "telefone1", length = 14)
	public String getTelefone1() {
		return this.telefone1;
	}

	public void setTelefone1(String telefone1) {
		this.telefone1 = telefone1;
	}

	@Column(name = "telefone2", length = 14)
	public String getTelefone2() {
		return this.telefone2;
	}

	public void setTelefone2(String telefone2) {
		this.telefone2 = telefone2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pessoajuridica")
	public Set<Boleto> getBoletos() {
		return this.boletos;
	}

	public void setBoletos(Set<Boleto> boletos) {
		this.boletos = boletos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pessoajuridica")
	public Set<Cliente> getClientes() {
		return this.clientes;
	}

	public void setClientes(Set<Cliente> clientes) {
		this.clientes = clientes;
	}

}
