package com.rentstore.model;

// Generated 11/07/2013 17:45:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Setor generated by hbm2java
 */
@Entity
@Table(name = "setor", catalog = "concessionaria")
public class Setor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 628436993430447550L;
	private Integer idsetor;
	private String nome;
	private Set<Funcionario> funcionarios = new HashSet<Funcionario>(0);

	public Setor() {
	}

	public Setor(String nome, Set<Funcionario> funcionarios) {
		this.nome = nome;
		this.funcionarios = funcionarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idsetor", unique = true, nullable = false)
	public Integer getIdsetor() {
		return this.idsetor;
	}

	public void setIdsetor(Integer idsetor) {
		this.idsetor = idsetor;
	}

	@Column(name = "nome", length = 60)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "setores")
	public Set<Funcionario> getFuncionarios() {
		return this.funcionarios;
	}

	public void setFuncionarios(Set<Funcionario> funcionarios) {
		this.funcionarios = funcionarios;
	}

}
